import type { Metadata } from "next";
import { Playfair_Display, Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const radhiumz = localFont({
  src: "../assets/fonts/Radhiumz.ttf",
  display: "swap",
  variable: "--font-radhiumz",
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "GIMME - A financial inclusive world for everyone.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${playfair.variable} ${radhiumz.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
